namespace Lyt.CodeGenerators;

using static SyntaxFactory;
using PropertyTuple = (IPropertySymbol PropertySymbol, SemanticModel SemanticModel);

[Generator]
public sealed class ModelPropertyGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Lyt.Model.AutoNotifyPropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // RegisterPostInitializationOutput runs once, unconditionally.
        // Use it for output that does not depend on the user's code at all.
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("HelloWorld.g.cs", """
                // <auto-generated/>
                namespace Lyt.CodeGenerators.Generated;

                using System;
                public static class HelloWorld
                {
                    public static string Greet(this string name) => $"Hello, {name}!";
                }
                """);

        });

        var propertySymbols = context.ForAttributeWithMetadataNameAndOptions(
                AttributeFullName,
                predicate: (node, _) => node is PropertyDeclarationSyntax,
                transform: (ctx, _) => (PropertySymbol: (IPropertySymbol)ctx.TargetSymbol, ctx.SemanticModel))
            .Where(ctx => ctx.PropertySymbol.ContainingType is not null);

        var compilationAndProperties = context.CompilationProvider.Combine(propertySymbols.Collect());

        context.RegisterSourceOutput(compilationAndProperties, (spc, source) =>
        {
            var compilation = source.Left;
            var ctx = source.Right;
            if (ctx.IsDefaultOrEmpty)
            {
                return;
            }

            var groups = 
                ctx.GroupBy<PropertyTuple, INamedTypeSymbol?>(
                    p => p.PropertySymbol.ContainingType, SymbolEqualityComparer.Default);
            foreach (var group in groups)
            {
                var containingClass = group.Key;
                if (containingClass is null)
                {
                    continue;
                }

                if (!CheckContainingTypeIsPartial(spc, containingClass, "AutoNotifyPropertyAttribute"))
                {
                    continue;
                }

                var validProperties = new List<PropertyTuple>();
                foreach (var (property, model) in group)
                {
                    //if (!DiagnosticHelper.CheckPropertyDeclaration(spc, property, "AutoNotifyPropertyAttribute"))
                    //{
                    //    continue;
                    //}

                    var attribute = 
                        property
                            .GetAttributes()
                            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == AttributeFullName);
                    if (attribute is null)
                    {
                        continue;
                    }

                    //if (!DiagnosticHelper.CheckStyledPropertyMethodReferences(spc, containingClass, property, attribute))
                    //    continue;

                    validProperties.Add((property, model));
                }

                if (validProperties.Count == 0)
                {
                    continue;
                }

                string sourceCode = GenerateClassSource(compilation, containingClass, validProperties);
                spc.AddSource(
                    $"{containingClass.ContainingNamespace.ToDisplayString()}.{containingClass.Name}.g.cs",
                    SourceText.From(sourceCode, Encoding.UTF8));
            }
        });
    }

    public static bool CheckContainingTypeIsPartial(
         SourceProductionContext spc,
         INamedTypeSymbol containingClass,
         string attributeName
     )
    {
        if (containingClass.DeclaringSyntaxReferences
            .Any(r => r.GetSyntax() is ClassDeclarationSyntax cls &&
                      cls.Modifiers.Any(SyntaxKind.PartialKeyword)))
        {
            return true;
        }

        spc.ReportDiagnostic(Diagnostic.Create(
            GeneratorDiagnostics.ContainingTypeMustBePartial,
            containingClass.Locations.FirstOrDefault(),
            containingClass.Name, attributeName));
        return false;
    }

    private static string GenerateClassSource(Compilation compilation, INamedTypeSymbol classSymbol, ICollection<PropertyTuple> properties)
    {
        return "// <auto-generated/>\r\n";
        //var compilationUnit =
        //    CompilationUnit()
        //    .AddMembers(GenerateContent(compilation, classSymbol, properties))
        //    .WithLeadingTrivia(
        //        ParseLeadingTrivia("// <auto-generated/>\r\n")
        //        .Add(Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true)))
        //        .Add(Trivia(PragmaWarningDirectiveTrivia(Token(SyntaxKind.DisableKeyword), true))));

        //return SyntaxTree(compilationUnit.NormalizeWhitespace()).ToString();
    }

    //private static NamespaceDeclarationSyntax GenerateContent(
    //    Compilation compilation, INamedTypeSymbol classSymbol, ICollection<PropertyTuple> properties)
    //{
    //    string namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
    //    string className = classSymbol.Name;
    //    var doNotGenerateOnPropertyChangedAttributeSymbols = 
    //        compilation.GetTypesByMetadataName("PropertyGenerator.Avalonia.DoNotGenerateOnPropertyChangedAttribute");
    //    bool generateOnPropertyChanged = false;
    //        //!classSymbol.HasAttributeWithAnyType(doNotGenerateOnPropertyChangedAttributeSymbols) &&
    //        //!compilation.Assembly.HasAttributeWithAnyType(doNotGenerateOnPropertyChangedAttributeSymbols);

    //    var classDeclaration = ClassDeclaration(className).AddModifiers(Token(SyntaxKind.PartialKeyword));
    //    foreach (var (property, model) in properties)
    //    {
    //        classDeclaration = classDeclaration.AddMembers(GenerateFieldDeclaration(compilation, classSymbol, property, model));
    //        classDeclaration = classDeclaration.AddMembers(GeneratePropertyDeclaration(property));
    //        if (generateOnPropertyChanged)
    //        {
    //            classDeclaration = classDeclaration.AddMembers(GenerateChangedMethod(property));
    //        }
    //    }

    //    classDeclaration = 
    //        classDeclaration.WithLeadingTrivia(ParseLeadingTrivia($"/// <inheritdoc cref=\"{className}\"/>\r\n"));
    //    var namespaceDeclarationSyntax = NamespaceDeclaration(ParseName(namespaceName)).AddMembers(classDeclaration);
    //    return namespaceDeclarationSyntax;
    //}

    //private static FieldDeclarationSyntax GenerateFieldDeclaration(Compilation compilation, INamedTypeSymbol classSymbol, IPropertySymbol propertySymbol, SemanticModel model)
    //{
    //    var propertyName = propertySymbol.Name;
    //    var className = classSymbol.GetFullyQualifiedName();
    //    var styledPropertySymbolName = compilation.GetTypeByMetadataName("Avalonia.StyledProperty`1")!
    //        .Construct(propertySymbol.Type).GetFullyQualifiedNameWithNullabilityAnnotations();
    //    var avaloniaPropertySymbolName =
    //        compilation.GetTypeByMetadataName("Avalonia.AvaloniaProperty")!.GetFullyQualifiedName();
    //    var attribute = propertySymbol.GetAttributes().FirstOrDefault(p => p.AttributeClass!.ToDisplayString() == AttributeFullName)!;

    //    var defaultValue = DefaultValueHelper.GetDefaultValue(
    //        attribute,
    //        propertySymbol,
    //        model,
    //        CancellationToken.None);

    //    List<ArgumentSyntax> arguments =
    //    [
    //        Argument(NameOfExpression(propertyName))
    //            .WithNameColon(NameColon(IdentifierName("name")))
    //    ];

    //    if (defaultValue is not AvaloniaPropertyDefaultValue.UnsetValue)
    //    {
    //        if (defaultValue is AvaloniaPropertyDefaultValue.Callback callback)
    //        {
    //            arguments.Add(Argument(InvocationExpression(IdentifierName(callback.MethodName)))
    //                .WithNameColon(NameColon(IdentifierName("defaultValue"))));
    //        }
    //        else
    //        {
    //            arguments.Add(Argument(IdentifierName(defaultValue.ToString()))
    //                .WithNameColon(NameColon(IdentifierName("defaultValue"))));
    //        }
    //    }

    //    if (attribute.TryGetNamedArgument("Validate", out var validate))
    //    {
    //        arguments.Add(Argument(IdentifierName(validate.Value!.ToString()))
    //            .WithNameColon(NameColon(IdentifierName("validate"))));
    //    }

    //    if (attribute.TryGetNamedArgument("Coerce", out var coerce))
    //    {
    //        arguments.Add(Argument(IdentifierName(coerce.Value!.ToString()))
    //            .WithNameColon(NameColon(IdentifierName("coerce"))));
    //    }

    //    if (attribute.TryGetNamedArgument("EnableDataValidation", out var enableDataValidation))
    //    {
    //        arguments.Add(Argument(IdentifierName(enableDataValidation.Value!.ToString().ToLower()))
    //            .WithNameColon(NameColon(IdentifierName("enableDataValidation"))));
    //    }

    //    if (attribute.TryGetNamedArgument("Inherits", out var inherits))
    //    {
    //        arguments.Add(Argument(IdentifierName(inherits.Value!.ToString().ToLower()))
    //            .WithNameColon(NameColon(IdentifierName("inherits"))));
    //    }

    //    if (attribute.TryGetNamedArgument("DefaultBindingMode", out var defaultBindingMode))
    //    {
    //        arguments.Add(Argument(IdentifierName(TypedConstantInfo.Create(defaultBindingMode).ToString()))
    //            .WithNameColon(NameColon(IdentifierName("defaultBindingMode"))));
    //    }

    //    var fieldDeclaration = FieldDeclaration(
    //            VariableDeclaration(IdentifierName(styledPropertySymbolName))
    //                .WithVariables(SingletonSeparatedList(VariableDeclarator(Identifier($"{propertyName}Property"))
    //                    .WithInitializer(EqualsValueClause(InvocationExpression(MemberAccessExpression(
    //                            SyntaxKind.SimpleMemberAccessExpression,
    //                            IdentifierName(avaloniaPropertySymbolName),
    //                            GenericName(Identifier("Register"))
    //                                .AddTypeArgumentListArguments(
    //                                    IdentifierName(className),
    //                                    propertySymbol.Type.GetTypeSyntax())))
    //                        .AddArgumentListArguments([.. arguments]))))))
    //        .AddModifiers([
    //            ..propertySymbol.DeclaredAccessibility.GetAccessibilityModifiers(), Token(SyntaxKind.StaticKeyword),
    //            Token(SyntaxKind.ReadOnlyKeyword)
    //        ])
    //        .AddAttributeLists(AttributeList(SingletonSeparatedList(GeneratedCodeAttribute())))
    //        .WithLeadingTrivia(ParseLeadingTrivia(
    //            $$"""
    //              /// <summary>
    //              /// The backing <see cref="global::Avalonia.StyledProperty{TValue}"/> instance for <see cref="{{propertyName}}"/>.
    //              /// </summary>

    //              """));
    //    return fieldDeclaration;
    //}
}

